[project]
name = "mitchel-lab-cell-tracking"
version = "0.1.0"
description = "A cell-tracking software for cell microscopy. Orginally developed for the Mitchel Lab at Wesleyan University."
authors = [
    {name = "Ziyad Rahman",email = "zrahman3004@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<3.14" 
package-mode = false
dependencies = [
    "matplotlib (>=3.10.6,<4.0.0)",
    "tifffile (>=2025.10.4,<2026.0.0)",
    "opencv-python (>=4.12.0.88,<5.0.0.0)",
    "scipy (>=1.16.2,<2.0.0)",
    "torch (>=2.8.0,<3.0.0)",
    "torchvision (>=0.23.0,<0.24.0)",
    "click (>=8.3.1,<9.0.0)",
    "pytest (>=9.0.1,<10.0.0)"
]

[tool.poetry]

[tool.poetry.group.dev.dependencies]
black = "^25.9.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
